# Generated by Django 2.2.13 on 2020-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.BigIntegerField()),
            ],
        ),
    ]
